/* ============================================================================
   OmniSource — core.js
   ----------------------------------------------------------------------------
   The shared brain of the site: theme, clipboard, toasts, formatting helpers,
   the global search engine + ⌘K palette (with history and popular searches),
   PWA plumbing (service worker, install prompt) and scroll-reveal motion.

   Loaded by every page, including the static app detail pages generated by
   src/omnisource/app_pages.py. It is dependency-free, works offline (all data
   it needs is cached by sw.js) and never blocks first paint (deferred).

   Page-specific rendering lives in js/site.js (home / compare / status /
   analytics / install / search).
   ========================================================================== */
(function () {
  'use strict';

  /* ------------------------------------------------------------------ root */
  // Resolve the site root from a loaded asset URL. `document.currentScript`
  // is null for deferred scripts (every page loads core.js with `defer`),
  // so we look the tag up in the DOM instead. Falling back to the pathname
  // keeps GitHub Pages project sites (/OmniSource/) working even if the
  // script tag is rewritten.
  function detectRoot() {
    function fromUrl(value, needle) {
      if (!value) return '';
      try { value = new URL(value, location.href).href; } catch (e) { return ''; }
      var idx = value.lastIndexOf(needle);
      return idx === -1 ? '' : value.slice(0, idx);
    }
    var scripts = document.getElementsByTagName('script');
    for (var i = 0; i < scripts.length; i++) {
      var rooted = fromUrl(scripts[i].src, '/js/core.js');
      if (rooted) return rooted.replace(/\/+$/, '');
    }
    var links = document.querySelectorAll('link[rel="stylesheet"]');
    for (var j = 0; j < links.length; j++) {
      var fromCss = fromUrl(links[j].href, '/assets/design-system/');
      if (fromCss) return fromCss.replace(/\/+$/, '');
    }
    var path = (location.pathname || '/').replace(/\/index\.html$/, '');
    path = path.replace(/\/(compare|status|analytics|install|search)(\/.*)?$/, '');
    path = path.replace(/\/apps\/[^/]+(\/.*)?$/, '');
    path = path.replace(/\/+$/, '');
    return path ? location.origin + path : location.origin;
  }
  var ROOT = detectRoot();
  function url(path) {
    if (!path) return '#';
    if (/^https?:\/\//.test(path)) return path;
    return ROOT + (path.charAt(0) === '/' ? path : '/' + path);
  }
  function asset(name) {
    var file = String(name || 'OmniSource.png').replace(/^assets\//, '');
    return url('assets/' + file);
  }
  /* Icon fields arrive in three shapes: absolute URLs (the generated feeds
     write https://site/assets/X.webp), root-relative ones (feeds/compare.json
     stores "assets/X.webp") and bare file names (api/catalog.json stores
     "X.webp"). Resolving the relative shapes with `cleanUrl` is wrong away
     from the site root — `new URL('assets/X.webp', location.href)` on
     /compare/ answers "http://…/compare/assets/X.webp", a 404 for every icon
     on the page — so resolve them against the detected ROOT instead. */
  function icon(value, fallback) {
    var raw = String(value == null ? '' : value).trim();
    if (!raw || raw === '#') return url(fallback || 'assets/OmniSource.png');
    if (/^data:/i.test(raw) || /^(?:https?:)?\/\//i.test(raw)) return raw;
    return asset(raw.replace(/^(?:\.\.?\/)+/, '').replace(/^\/+/, ''));
  }

  /* --------------------------------------------------------------- helpers */
  var $ = function (sel, root) { return (root || document).querySelector(sel); };
  var $$ = function (sel, root) { return Array.prototype.slice.call((root || document).querySelectorAll(sel)); };

  /* Per-page JSON memo. Several modules ask for the same document (site.js,
     the src/js data layer, per-page widgets); before this, /compare/ fetched
     11 feeds twice — 34 requests and 3.4 MB for one page. In-flight requests
     share a single promise and finished ones are reused for JSON_TTL_MS, so a
     feed is downloaded once per page load. Callers treat these documents as
     read-only; the memo hands out the same object rather than a copy because
     cloning a 700 KB catalog on every read costs more than it saves. */
  var jsonMemo = Object.create(null);
  var JSON_TTL_MS = 5 * 60 * 1000;

  var OS = {
    ROOT: ROOT,
    url: url,
    asset: asset,
    icon: icon,
    $: $,
    $$: $$,
    animateCount: animateCount,
    reducedMotion: window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches,

    esc: function (value) {
      return String(value == null ? '' : value).replace(/[&<>'"]/g, function (ch) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[ch];
      });
    },

    cleanUrl: function (value) {
      try {
        var u = new URL(value, location.href);
        return ['http:', 'https:'].indexOf(u.protocol) !== -1 ? u.href : '#';
      } catch (e) { return '#'; }
    },

    /* Translate a UI string through the runtime locale (src/js/i18n.js).
     * Falls back to the embedded English template when the locale bundle
     * has not loaded yet (or i18n.js failed), so renderers never flash raw
     * translation keys. Templates use ${name} placeholders. */
    t: function (key, params, fallback) {
      try {
        if (window.OmniI18n && window.OmniI18n.loaded && window.OmniI18n.loaded('en')) {
          return window.OmniI18n.t(key, params);
        }
      } catch (e) { /* fall through to the English fallback */ }
      var out = String(fallback != null ? fallback : key);
      if (params) {
        Object.keys(params).forEach(function (name) {
          out = out.split('${' + name + '}').join(String(params[name]));
        });
      }
      return out;
    },

    parseDate: function (value) {
      if (!value) return null;
      var d = new Date(String(value).length === 10 ? String(value) + 'T12:00:00Z' : value);
      return isNaN(d.valueOf()) ? null : d;
    },

    fmtDate: function (value) {
      var d = OS.parseDate(value);
      return d
        ? d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
        : (value || 'Unknown');
    },

    timeAgo: function (value) {
      var d = OS.parseDate(value);
      if (!d) return 'Unknown';
      var days = Math.max(0, Math.round((Date.now() - d.getTime()) / 86400000));
      if (days === 0) return OS.t('common.today', null, 'today');
      if (days === 1) return OS.t('common.yesterday', null, 'yesterday');
      if (days < 30) return OS.t('common.daysAgo', { count: days }, '${count}d ago');
      if (days < 365) return OS.t('common.monthsAgo', { count: Math.round(days / 30) }, '${count}mo ago');
      return OS.t('common.yearsAgo', { count: Math.round(days / 365) }, '${count}y ago');
    },

    fmtBytes: function (bytes) {
      if (!Number(bytes)) return 'Unknown';
      var units = ['B', 'KB', 'MB', 'GB'];
      var i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
      return (bytes / Math.pow(1024, i)).toFixed(i > 1 ? 1 : 0) + ' ' + units[i];
    },

    fetchJSON: function (path, timeoutMs) {
      var hit = jsonMemo[path];
      if (hit) {
        if (hit.pending) return hit.pending;
        if (Date.now() - hit.at < JSON_TTL_MS) return Promise.resolve(hit.value);
      }
      var controller = new AbortController();
      var id = setTimeout(function () { controller.abort(); }, timeoutMs || 8000);
      var pending = fetch(url(path), { signal: controller.signal, headers: { Accept: 'application/json' } })
        .then(function (res) { return res.ok ? res.json() : null; })
        .catch(function () { return null; })
        .finally(function () { clearTimeout(id); });
      jsonMemo[path] = { pending: pending, at: 0, value: null };
      pending.then(function (value) {
        jsonMemo[path] = { pending: null, at: Date.now(), value: value };
      });
      return pending;
    },

    /* Toast. A non-blocking, fixed-position status line: it never takes part
       in layout, so showing one cannot shift the page (requirement: the
       "new version" notice must not move what the reader is looking at).

       Options (all optional):
         actions:    [{ label, primary, onSelect, keepOpen }] — rendered as real
                     <button>s inside the toast. Used by the service-worker
                     update prompt; without them the toast is what it always
                     was, a two-second confirmation line.
         persistent: keep it on screen until an action is chosen or
                     OS.hideToast() runs.
         duration:   override the auto-hide delay in ms (0 = persistent). */
    toast: function (message, options) {
      var opts = options || {};
      var node = $('#toast');
      if (!node) {
        // Pages that do not ship the toast markup (favorites / collections)
        // still get the same shared component, created once on demand.
        node = document.createElement('div');
        node.className = 'toast';
        node.id = 'toast';
        node.setAttribute('role', 'status');
        node.setAttribute('aria-live', 'polite');
        node.innerHTML = '<svg aria-hidden="true" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg><span class="toast-text"></span>';
        document.body.appendChild(node);
      }
      var label = node.querySelector('.toast-text') || node.querySelector('span');
      if (label) {
        label.classList.add('toast-text');
        label.textContent = String(message == null ? '' : message);
      }

      var actions = Array.isArray(opts.actions) ? opts.actions : [];
      var tray = node.querySelector('.toast-actions');
      if (!tray) {
        tray = document.createElement('div');
        tray.className = 'toast-actions';
        node.appendChild(tray);
      }
      tray.textContent = '';
      tray.hidden = !actions.length;
      actions.forEach(function (action) {
        if (!action || !action.label) return;
        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'toast-action' + (action.primary ? ' primary' : '');
        button.textContent = String(action.label);
        button.addEventListener('click', function (event) {
          event.preventDefault();
          event.stopPropagation();
          if (button.disabled) return;
          if (!action.keepOpen) OS.hideToast();
          try {
            if (typeof action.onSelect === 'function') action.onSelect();
          } catch (error) { /* an action must never break the page */ }
        });
        tray.appendChild(button);
      });

      node.classList.toggle('has-actions', actions.length > 0);
      node.classList.add('show');
      clearTimeout(OS._toastTimer);
      var duration = opts.persistent ? 0 : (opts.duration == null ? 2600 : opts.duration);
      if (duration > 0) {
        OS._toastTimer = setTimeout(function () { node.classList.remove('show'); }, duration);
      }
      return node;
    },

    hideToast: function () {
      clearTimeout(OS._toastTimer);
      var node = $('#toast');
      if (!node) return;
      node.classList.remove('show');
      // Drop stale action handlers so a dismissed prompt cannot be triggered
      // by a later click on a hidden button.
      var tray = node.querySelector('.toast-actions');
      node.classList.remove('has-actions');
      if (tray) {
        setTimeout(function () {
          if (node.classList.contains('show')) return;
          tray.textContent = '';
          tray.hidden = true;
        }, 320);
      }
    },

    copy: function (text, successMsg) {
      var value = String(text == null ? '' : text);
      function copied() { OS.toast(successMsg || 'Copied to clipboard'); }
      /* The Clipboard API needs a secure context and a user gesture, and it is
         absent in older WebViews — the source URL is the one thing a reader
         copies on a phone, so a failure must not be reported as a success.
         `execCommand` is the fallback; when that fails too, the value is left
         selected so the reader can copy it by hand. */
      function fallback() {
        var y = window.scrollY || window.pageYOffset || 0;
        var input = document.createElement('textarea');
        input.value = value;
        input.setAttribute('readonly', 'readonly');
        input.setAttribute('aria-hidden', 'true');
        input.style.cssText = 'position:fixed;top:0;left:0;width:1px;height:1px;opacity:0';
        document.body.appendChild(input);
        var ok = false;
        try {
          input.select();
          if (input.setSelectionRange) input.setSelectionRange(0, value.length);
          ok = document.execCommand('copy');
        } catch (error) { ok = false; }
        // Selecting a fixed node can nudge the viewport on iOS; put it back.
        if ((window.scrollY || 0) !== y) window.scrollTo(0, y);
        if (ok) input.remove();
        if (ok) copied();
        else OS.toast('Copy blocked — press and hold the URL to copy it', { duration: 4200 });
      }
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(value).then(copied, fallback);
      } else {
        fallback();
      }
    }
  };
  window.OS = OS;

  /* ----------------------------------------------------------------- theme */
  var THEMES = ['auto', 'light', 'dark'];
  function currentTheme() {
    return document.documentElement.dataset.theme || 'auto';
  }
  function setTheme(theme) {
    if (THEMES.indexOf(theme) === -1) theme = 'auto';
    document.documentElement.dataset.theme = theme;
    try { localStorage.setItem('omnisource-theme', theme); } catch (e) { /* private mode */ }
    var meta = $('#themeColor');
    if (meta) {
      var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
      var dark = theme === 'dark' || (theme === 'auto' && prefersDark);
      meta.content = dark ? '#07070f' : '#e8eef8';
    }
    var btn = $('#themeButton');
    if (btn) {
      var labels = { auto: 'Theme: system', light: 'Theme: light', dark: 'Theme: dark' };
      btn.title = labels[theme];
      btn.setAttribute('aria-label', labels[theme] + '. Change color theme');
    }
  }
  function cycleTheme() {
    setTheme(THEMES[(THEMES.indexOf(currentTheme()) + 1) % THEMES.length]);
  }

  /* --------------------------------------------------------------- clipboard */
  document.addEventListener('click', function (event) {
    var target = event.target.closest ? event.target.closest('[data-copy]') : null;
    if (!target) return;
    OS.copy(target.getAttribute('data-copy') || '', target.getAttribute('data-copy-msg'));
  });

  /* ============================================================================
     Search engine — weighted fuzzy matching over the generated search index.
     Same contract as feeds/search-index.json (Fuse.js compatible): name,
     shortDescription, description, category, tags, developer, bundleId.
     ========================================================================== */
  var SEARCH_KEYS = [
    { name: 'name', weight: 0.35 },
    { name: 'shortDescription', weight: 0.15 },
    { name: 'description', weight: 0.10 },
    { name: 'category', weight: 0.08 },
    { name: 'tags', weight: 0.10 },
    { name: 'developer', weight: 0.10 },
    { name: 'bundleId', weight: 0.12 }
  ];
  var SEARCH_THRESHOLD = 0.38;
  /* A single character is a legitimate query — "y" for YouTube, "v" for
     Vanced — and the old two-character minimum made the palette answer it with
     the popular chips and nothing else, as if the keystroke had been dropped.
     Scoring every field at 0.38 still filtered those out (a one-character name
     match is worth 0.35 x 0.85 = 0.30), so short queries get their own, lower
     bar: at 0.12 only a name hit (0.35 x 0.65 = 0.23) and combinations of
     name + metadata clear it, which is exactly the "apps called something with
     this letter" answer a single keystroke deserves. */
  var SEARCH_MIN_CHARS = 1;
  var SEARCH_SHORT_THRESHOLD = 0.12;

  var Search = {
    docs: [],          // index documents
    trending: null,    // feeds/trending.json (for "popular" chips)
    ready: null,       // promise

    load: function () {
      if (!this.ready) {
        /* js/site.js may already have warmed the index on the home page (its
           idle tier); reuse it instead of fetching and parsing 120 KB twice. */
        var index = this.docs.length
          ? Promise.resolve(this.docs)
          : OS.fetchJSON('feeds/search-index.json').then(function (doc) {
            Search.docs = (doc && doc.documents) || [];
            return Search.docs;
          });
        this.ready = index.then(function (docs) {
          return Search.fetchTrending().then(function () { return docs; });
        });
      }
      return this.ready;
    },

    fetchTrending: function () {
      return OS.fetchJSON('feeds/trending.json', 5000).then(function (doc) {
        Search.trending = doc;
        return doc;
      });
    },

    score: function (query, value) {
      if (!value) return 0;
      var text = String(value).toLowerCase();
      if (!text) return 0;
      if (text === query) return 1;
      if (text.indexOf(query) === 0) return 0.85;
      if (text.indexOf(query) !== -1) return 0.65;
      var tokens = query.split(/\s+/).filter(Boolean);
      if (!tokens.length) return 0;
      var hits = 0;
      for (var i = 0; i < tokens.length; i++) {
        if (text.indexOf(tokens[i]) !== -1) hits++;
      }
      if (!hits) return 0;
      return 0.45 * (hits / tokens.length);
    },

    search: function (query) {
      var q = String(query || '').toLowerCase().trim();
      if (q.length < SEARCH_MIN_CHARS) return [];
      var threshold = q.length === 1 ? SEARCH_SHORT_THRESHOLD : SEARCH_THRESHOLD;
      var results = [];
      for (var i = 0; i < this.docs.length; i++) {
        var doc = this.docs[i];
        var score = 0;
        for (var k = 0; k < SEARCH_KEYS.length; k++) {
          var key = SEARCH_KEYS[k];
          var field = doc[key.name];
          if (Array.isArray(field)) {
            for (var f = 0; f < field.length; f++) {
              score += key.weight * this.score(q, field[f]);
            }
          } else {
            score += key.weight * this.score(q, field || '');
          }
        }
        if (score >= threshold) results.push({ doc: doc, score: score });
      }
      results.sort(function (a, b) { return b.score - a.score; });
      return results.slice(0, 10);
    },

    highlight: function (text, query) {
      var value = OS.esc(text);
      if (!query) return value;
      var parts = String(query).split(/\s+/).filter(function (t) { return t.length >= SEARCH_MIN_CHARS; });
      if (!parts.length) return value;
      var re = new RegExp('(' + parts.map(function (t) {
        return t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      }).join('|') + ')', 'ig');
      return value.replace(re, '<mark>$1</mark>');
    },

    popular: function () {
      var items = [];
      if (this.trending && Array.isArray(this.trending.trending)) {
        this.trending.trending.slice(0, 6).forEach(function (t) {
          items.push({ label: t.name, slug: t.slug });
        });
      }
      if (!items.length) {
        this.docs.slice(0, 6).forEach(function (d) {
          items.push({ label: d.name, slug: d.slug });
        });
      }
      return items;
    },

    topCategories: function (limit) {
      var counts = {};
      this.docs.forEach(function (d) {
        var c = d.category || 'other';
        counts[c] = (counts[c] || 0) + 1;
      });
      return Object.keys(counts)
        .sort(function (a, b) { return counts[b] - counts[a]; })
        .slice(0, limit || 5);
    }
  };
  OS.Search = Search;

  /* ============================================================================
     Catalog loader
     ----------------------------------------------------------------------------
     Pages that need the discovery catalog (the /collections/ and /favorites/
     views) all read the same API document, but only the flat/API URL families
     are guaranteed to exist in a deployed site — a preview served straight from
     the sources has just feeds/. Resolve the document from every published
     location, in order, so those pages can never be left empty by a missing
     copy: /api/catalog.json → /feeds/discovery.json → /discovery.json.
     ========================================================================== */
  var CATALOG_SOURCES = ['api/catalog.json', 'feeds/discovery.json', 'discovery.json'];

  OS.loadCatalog = function (timeoutMs) {
    var chain = Promise.resolve(null);
    CATALOG_SOURCES.forEach(function (path) {
      chain = chain.then(function (doc) {
        if (doc && Array.isArray(doc.apps)) return doc;
        return OS.fetchJSON(path, timeoutMs || 6000);
      });
    });
    return chain.then(function (doc) {
      var apps = doc && Array.isArray(doc.apps) ? doc.apps : [];
      if (apps.length) window.OS_CATALOG = apps;
      return apps;
    });
  };

  /* ============================================================================
     Global search palette (⌘K / Ctrl+K / "/")
     ----------------------------------------------------------------------------
     Injected once into <body>. Instant results with keyboard navigation,
     search history (localStorage) and popular searches while empty.
     ========================================================================== */
  var HISTORY_KEY = 'omnisource-search-history';
  var HISTORY_MAX = 8;

  var Palette = {
    el: null,
    input: null,
    body: null,
    isOpen: false,
    selected: 0,
    rows: [],          // visible, in DOM order: {type:'app'|'history', slug, name, q}
    lastFocus: null,

    build: function () {
      if (this.el) return;
      var el = document.createElement('div');
      el.className = 'os-palette';
      el.setAttribute('role', 'dialog');
      el.setAttribute('aria-modal', 'true');
      el.setAttribute('aria-label', 'Search OmniSource');
      el.innerHTML =
        '<div class="os-palette-backdrop" data-palette-close></div>' +
        '<div class="os-palette-panel">' +
          '<form class="os-palette-form" role="search">' +
            '<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="m20 20-4-4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>' +
            '<input class="os-palette-input" type="search" placeholder="Search apps, bundle IDs, developers, categories…" ' +
            'autocomplete="off" spellcheck="false" aria-label="Search OmniSource" aria-expanded="false">' +
            '<kbd>esc</kbd>' +
          '</form>' +
          '<div class="os-palette-body" role="listbox" aria-label="Search results"></div>' +
          '<div class="os-palette-hints" aria-hidden="true">' +
            '<span><kbd>↑</kbd><kbd>↓</kbd> navigate</span>' +
            '<span><kbd>↵</kbd> open</span>' +
            '<span><kbd>esc</kbd> close</span>' +
          '</div>' +
        '</div>';
      document.body.appendChild(el);
      this.el = el;
      this.input = el.querySelector('.os-palette-input');
      this.body = el.querySelector('.os-palette-body');

      el.addEventListener('mousedown', function (event) {
        if (event.target.closest('[data-palette-close]')) Palette.close();
      });
      el.querySelector('form').addEventListener('submit', function (event) {
        event.preventDefault();
        Palette.activateSelected();
      });
      this.input.addEventListener('input', function () { Palette.render(this.value); });
      this.input.addEventListener('keydown', function (event) {
        if (event.key === 'ArrowDown') {
          event.preventDefault();
          Palette.selected = Math.min(Palette.rows.length - 1, Palette.selected + 1);
          Palette.paintSelection();
        } else if (event.key === 'ArrowUp') {
          event.preventDefault();
          Palette.selected = Math.max(0, Palette.selected - 1);
          Palette.paintSelection();
        } else if (event.key === 'Enter') {
          event.preventDefault();
          Palette.activateSelected();
        } else if (event.key === 'Escape') {
          Palette.close();
        }
      });
    },

    open: function () {
      this.build();
      if (this.isOpen) { this.input.focus(); return; }
      this.lastFocus = document.activeElement;
      this.isOpen = true;
      if (OS.closeNav) OS.closeNav();
      document.body.style.overflow = 'hidden';
      this.el.classList.add('is-open');
      this.input.value = '';
      this.selected = 0;
      this.render('');
      var self = this;
      // Focus after the entrance animation so it is visible.
      requestAnimationFrame(function () { self.input.focus(); });
      Search.load();
    },

    close: function () {
      if (!this.isOpen) return;
      this.isOpen = false;
      this.el.classList.remove('is-open');
      document.body.style.overflow = '';
      if (this.lastFocus && this.lastFocus.focus) this.lastFocus.focus();
    },

    /* -- history ----------------------------------------------------------- */
    history: function () {
      try {
        var list = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]');
        return Array.isArray(list) ? list : [];
      } catch (e) { return []; }
    },

    remember: function (entry) {
      try {
        var list = this.history().filter(function (item) {
          return !(item.q === entry.q && item.slug === entry.slug);
        });
        list.unshift(entry);
        localStorage.setItem(HISTORY_KEY, JSON.stringify(list.slice(0, HISTORY_MAX)));
      } catch (e) { /* private mode */ }
    },

    clearHistory: function () {
      try { localStorage.removeItem(HISTORY_KEY); } catch (e) { /* ignore */ }
      this.render(this.input.value);
    },

    /* -- rendering ---------------------------------------------------------- */
    appRow: function (doc, query, index) {
      var name = OS.Search.highlight(doc.name || '', query);
      var sub = OS.Search.highlight(doc.developer || doc.subtitle || '', query);
      var icon = asset(doc.icon || 'OmniSource.png');
      return '<a class="os-palette-row" href="' + OS.esc(url('apps/' + (doc.slug || doc.id) + '/')) + '" ' +
        'data-index="' + index + '" aria-selected="false" role="option">' +
        '<img src="' + OS.esc(icon) + '" alt="" width="38" height="38" loading="lazy">' +
        '<span class="info"><b>' + name + '</b><span>' + sub + '</span></span>' +
        '<span class="meta">' + OS.esc(String(doc.bundleId || '').slice(0, 30)) + '</span>' +
        '</a>';
    },

    historyRow: function (item, index) {
      return '<button class="os-palette-row" type="button" data-index="' + index + '" ' +
        'data-history="' + OS.esc(item.q) + '" aria-selected="false" role="option">' +
        '<svg viewBox="0 0 24 24" width="38" height="38" style="flex:none" aria-hidden="true">' +
        '<circle cx="12" cy="12" r="9" fill="none" stroke="var(--faint)" stroke-width="1.4"/>' +
        '<path d="M12 7v5l3.2 2" fill="none" stroke="var(--faint)" stroke-width="1.4" stroke-linecap="round"/></svg>' +
        '<span class="info"><b>' + OS.esc(item.q) + '</b><span>' + OS.esc(OS.t('search.recentSearch', null, 'recent search')) + '</span></span>' +
        '<span class="meta">' + (item.name ? OS.esc(item.name) : '') + '</span>' +
        '</button>';
    },

    render: function (query) {
      if (!this.body) return;
      var q = String(query || '').trim();

      if (q.length < SEARCH_MIN_CHARS) {
        this.renderEmptyState();
        return;
      }

      Search.load().then(function () {
        if (!Palette.isOpen) return;
        var results = Search.search(q);
        if (!results.length) {
          Palette.body.innerHTML = '<div class="os-palette-empty">' +
            OS.esc(OS.t('search.noMatches', { q: q }, 'No matches for “${q}”.')) + ' ' +
            OS.esc(OS.t('search.noResultsHint', null, 'Try a name, bundle ID, developer or tag.')) + '</div>';
          Palette.rows = [];
          return;
        }
        var html = '<div class="os-palette-group"><h4 class="os-palette-heading">' + OS.esc(OS.t('nav.apps', null, 'Apps')) + '</h4>' +
          results.map(function (item, i) { return Palette.appRow(item.doc, q, i); }).join('') +
          '</div>';
        Palette.body.innerHTML = html;
        Palette.rows = results.map(function (item) {
          return { type: 'app', slug: item.doc.slug || item.doc.id, name: item.doc.name, q: q };
        });
        Palette.selected = 0;
        Palette.paintSelection();
      });
    },

    renderEmptyState: function () {
      var history = this.history();
      var popular = Search.popular();
      var categories = Search.topCategories(5);
      var html = '';

      if (history.length) {
        html += '<div class="os-palette-group"><h4 class="os-palette-heading">' + OS.esc(OS.t('search.history', null, 'Recent')) + ' ' +
          '<button type="button" data-clear-history>' + OS.esc(OS.t('search.clear', null, 'Clear')) + '</button></h4>' +
          history.map(function (item, i) { return this.historyRow(item, i); }, this).join('') +
          '</div>';
      }

      if (popular.length) {
        html += '<div class="os-palette-group"><h4 class="os-palette-heading">' + OS.esc(OS.t('search.popular', null, 'Popular')) + '</h4>' +
          '<div class="os-palette-chips">' + popular.map(function (p) {
            return '<button type="button" class="os-palette-chip" data-chip="' + OS.esc(p.label) + '">' +
              OS.esc(p.label) + '</button>';
          }).join('') + '</div></div>';
      }

      if (categories.length) {
        html += '<div class="os-palette-group"><h4 class="os-palette-heading">' + OS.esc(OS.t('search.categories', null, 'Categories')) + '</h4>' +
          '<div class="os-palette-chips">' + categories.map(function (c) {
            return '<button type="button" class="os-palette-chip" data-chip="' + OS.esc(c) + '">' +
              OS.esc(c.charAt(0).toUpperCase() + c.slice(1)) + '</button>';
          }).join('') + '</div></div>';
      }

      if (!html) {
        html = '<div class="os-palette-empty">' + OS.esc(OS.t('search.noResultsHint', null, 'Try a name, bundle ID, developer or tag.')) + '</div>';
      }
      this.body.innerHTML = html;
      this.rows = history.map(function (item) {
        return { type: 'history', q: item.q, slug: item.slug || '', name: item.name || '' };
      });
      this.selected = 0;
      this.paintSelection();
    },

    paintSelection: function () {
      $$('[data-index]', this.body).forEach(function (row) {
        row.setAttribute('aria-selected', String(Number(row.dataset.index) === Palette.selected));
      });
      var selectedRow = this.body.querySelector('[aria-selected="true"]');
      if (selectedRow && selectedRow.scrollIntoView) {
        selectedRow.scrollIntoView({ block: 'nearest' });
      }
    },

    activateSelected: function () {
      var row = this.rows[this.selected];
      if (!row) return;
      if (row.type === 'history') {
        this.input.value = row.q;
        this.render(row.q);
        return;
      }
      this.remember({ q: this.input.value.trim() || row.name, slug: row.slug, name: row.name, ts: Date.now() });
      this.close();
      location.href = url('apps/' + row.slug + '/');
    }
  };
  OS.Palette = Palette;

  /* -- palette global events (chips, history clear, row clicks) ------------- */
  document.addEventListener('click', function (event) {
    var chip = event.target.closest ? event.target.closest('[data-chip]') : null;
    if (chip && Palette.el && chip.closest('.os-palette')) {
      Palette.input.value = chip.dataset.chip || '';
      Palette.render(chip.dataset.chip);
      Palette.input.focus();
      return;
    }
    if (event.target.closest && event.target.closest('[data-clear-history]') && Palette.el) {
      Palette.clearHistory();
      return;
    }
    var historyBtn = event.target.closest ? event.target.closest('[data-history]') : null;
    if (historyBtn && Palette.el && historyBtn.closest('.os-palette')) {
      Palette.input.value = historyBtn.dataset.history || '';
      Palette.render(historyBtn.dataset.history);
      Palette.input.focus();
    }
  });

  document.addEventListener('keydown', function (event) {
    var tag = (event.target.tagName || '').toLowerCase();
    var typing = tag === 'input' || tag === 'textarea' || tag === 'select' || event.target.isContentEditable;
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
      event.preventDefault();
      Palette.isOpen ? Palette.close() : Palette.open();
    } else if (event.key === '/' && !typing && !Palette.isOpen) {
      event.preventDefault();
      Palette.open();
    } else if (event.key === 'Escape' && Palette.isOpen) {
      Palette.close();
    }
  });

  /* -- palette mount points: nav search button + hero search bar ------------- */
  document.addEventListener('click', function (event) {
    var opener = event.target.closest
      ? event.target.closest('[data-open-palette]')
      : null;
    if (opener) {
      event.preventDefault();
      Palette.open();
    }
  });

  /* --------------------------------------------------------------------- PWA */

  /* Service-worker updates are opt-in, never automatic.

     What used to be here: the worker's `omnisource-sw-updated` message was
     answered with

         OS.toast('A new version is ready. Reloading…');
         setTimeout(function () { location.reload(); }, 1200);

     i.e. the page reloaded itself, wherever the reader happened to be — mid
     scroll, mid search, mid language choice — and again for every freshly
     activated worker. A reload is only the reader's decision to make, so the
     flow is now:

         new worker detected → keep the page exactly as it is
                             → unobtrusive toast: Update / Later
                             → Update → activate + ONE reload
                             → Later  → remembered for this tab session

     The notification itself is a fixed-position toast (no layout shift, no
     focus steal, no scroll interruption) and is raised at most once per
     worker version per tab. Nothing in this flow runs on scroll, touch or
     pointer events. */

  var SW_KEYS = {
    prompted: 'omnisource-sw-prompted:',
    later: 'omnisource-sw-later:',
    reloaded: 'omnisource-sw-reloaded:'
  };

  function readFlag(key) {
    try { return sessionStorage.getItem(key) === '1'; } catch (error) { return false; }
  }

  function writeFlag(key) {
    try { sessionStorage.setItem(key, '1'); } catch (error) { /* private mode */ }
  }

  /* One reload per worker version per tab, and only ever from a user choice. */
  var swReloading = false;

  function applyServiceWorkerUpdate(worker, version) {
    if (swReloading) return;
    swReloading = true;
    writeFlag(SW_KEYS.reloaded + (version || 'unknown'));
    var done = false;
    function reload() {
      if (done) return;
      done = true;
      location.reload();
    }
    // The new worker takes over asynchronously: reload as soon as it is in
    // charge, and at the latest after a short grace period, so the button
    // always does something visible even if `controllerchange` never fires.
    if (navigator.serviceWorker.addEventListener) {
      navigator.serviceWorker.addEventListener('controllerchange', reload);
    }
    try {
      if (worker && worker.postMessage) worker.postMessage({ type: 'omnisource-skip-waiting' });
    } catch (error) { /* the worker may already be active */ }
    setTimeout(reload, 1400);
  }

  function offerServiceWorkerUpdate(worker, version) {
    var tag = version || 'unknown';
    if (readFlag(SW_KEYS.reloaded + tag) || readFlag(SW_KEYS.later + tag)) return;
    if (readFlag(SW_KEYS.prompted + tag)) return; // never nag twice per tab
    writeFlag(SW_KEYS.prompted + tag);
    OS.toast(OS.t('pwa.updateReady', null, 'A new version of OmniSource is ready.'), {
      persistent: true,
      actions: [
        {
          label: OS.t('pwa.update', null, 'Update'),
          primary: true,
          onSelect: function () { applyServiceWorkerUpdate(worker, version); }
        },
        {
          label: OS.t('pwa.later', null, 'Later'),
          onSelect: function () { writeFlag(SW_KEYS.later + tag); }
        }
      ]
    });
  }

  function registerServiceWorker() {
    if (!('serviceWorker' in navigator)) return;
    var host = location.hostname.toLowerCase();
    var isSecure = location.protocol === 'https:' || host === 'localhost' || host === '127.0.0.1';
    if (!isSecure) return;
    /* Was this page already under a service worker when it booted?

       A first-ever visit installs the worker, `activate` claims the page and
       broadcasts `omnisource-sw-updated`. Only a page that was already
       controlled can be *updated*: on a first visit the new worker is an
       install, not an upgrade. */
    var hadController = Boolean(navigator.serviceWorker.controller);
    window.addEventListener('load', function () {
      navigator.serviceWorker.register(url('sw.js'), { updateViaCache: 'none' })
        .then(function (reg) {
          // The worker that is about to take over, if any: it is the one that
          // has to be told to skip waiting when the reader chooses Update.
          function pending() { return reg.waiting || reg.installing || navigator.serviceWorker.controller; }

          if (reg.waiting && hadController) offerServiceWorkerUpdate(pending(), reg.waiting.scriptURL);

          reg.addEventListener('updatefound', function () {
            var next = reg.installing;
            if (!next) return;
            next.addEventListener('statechange', function () {
              if (next.state !== 'installed') return;
              if (!navigator.serviceWorker.controller) return;
              offerServiceWorkerUpdate(next, next.scriptURL);
            });
          });

          navigator.serviceWorker.addEventListener('message', function (event) {
            if (!event.data || event.data.type !== 'omnisource-sw-updated') return;
            // A first visit installs the worker (no previous controller): only
            // an already-controlled page is being *updated*, and only that page
            // is ever offered a reload.
            if (!hadController || !navigator.serviceWorker.controller) return;
            offerServiceWorkerUpdate(pending(), event.data.version);
          });
        })
        .catch(function () { /* offline support is progressive */ });
    });
  }

  /* Generic QR dialog (static app pages).
     Pages carrying #qrButton[data-qr-feed] + #qrDialog get a working QR
     dialog with zero inline script. Home/install wire their own richer
     dialogs in js/site.js (different button ids), so this never conflicts. */
  function setupQrButton() {
    var button = $('#qrButton');
    var dialog = $('#qrDialog');
    if (!button || !dialog || !button.dataset.qrFeed) return;
    if (button._omniQrBound) return;
    button._omniQrBound = true;
    dialog.addEventListener('click', function (event) {
      if (event.target === dialog || (event.target.closest && event.target.closest('[data-close]'))) dialog.close();
    });
    button.addEventListener('click', function () {
      var img = $('#qrImage');
      if (img) {
        img.src = 'https://api.qrserver.com/v1/create-qr-code/?size=460x460&margin=0&data=' +
          encodeURIComponent(button.dataset.qrFeed);
      }
      if (!dialog.open) dialog.showModal();
    });
  }

  /* Header glass solidifies once the page scrolls (see .is-scrolled). */
  function setupHeaderState() {
    var header = $('.site-header') || $('.ap-header');
    if (!header) return;
    var ticking = false;
    var update = function () {
      ticking = false;
      header.classList.toggle('is-scrolled', window.scrollY > 8);
    };
    window.addEventListener('scroll', function () {
      if (!ticking) { ticking = true; requestAnimationFrame(update); }
    }, { passive: true });
    update();
  }

  /* Width at or below which the header collapses into the glass drawer.
     Keep in sync with the `@media (max-width: 1180px)` nav rules in
     assets/design-system/components.css — setupNavFit() below uses it to
     know when the inline row (and its overflow guard) is off duty. */
  var NAV_DRAWER_WIDTH = 1180;

  /* Mobile glass drawer. Injected so generated app pages get it for free. */
  function setupMobileNav() {
    var nav = $('.site-header .nav') || $('.ap-header-inner');
    if (!nav) return;
    var links = nav.querySelector('.nav-links');
    if (!links) return;
    if (!links.id) links.id = 'navLinks';

    var btn = $('#navToggle');
    if (!btn) {
      btn = document.createElement('button');
      btn.id = 'navToggle';
      btn.className = 'icon-button nav-toggle';
      btn.type = 'button';
      btn.setAttribute('aria-label', 'Open menu');
      btn.setAttribute('aria-expanded', 'false');
      btn.setAttribute('aria-controls', links.id);
      btn.innerHTML =
        '<svg class="icon-menu" aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>' +
        '<svg class="icon-close" aria-hidden="true" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>';
      nav.appendChild(btn);
    }

    var backdrop = $('.nav-backdrop');
    if (!backdrop) {
      backdrop = document.createElement('div');
      backdrop.className = 'nav-backdrop';
      backdrop.setAttribute('aria-hidden', 'true');
      document.body.appendChild(backdrop);
    }

    // The "More" dropdown lives inside the same .nav-links container: in the
    // phone drawer its items must always be visible (CSS hides the summary),
    // while on desktop it behaves as a hover/click menu.
    var moreMenus = $$('.nav-more', links);

    /* Focusable items inside the drawer, in DOM order (the "More" menu is a
       <details> whose links are always visible in drawer mode). */
    function focusables() {
      return $$('a[href], button:not([disabled]), summary, [tabindex]:not([tabindex="-1"])', links)
        .filter(function (node) { return node.getClientRects().length > 0; });
    }

    /* The scroll lock.

       A drawer that is open must not let the page behind it move — that is the
       whole point of the backdrop — but the lock must not cost native
       scrolling either. The two techniques that look obvious are both wrong
       here:

       - `body { overflow: hidden }` turns the body into a scroll container
         that never scrolls, which is exactly what `position: sticky` resolves
         against: the header un-sticks and the drawer (a fixed child of the
         header capsule) rides off the top of the screen while the page still
         believes the menu is open;
       - swallowing `wheel` / `touchmove` at the document level, plus
         `touch-action: none` on <html>, disables native panning for the whole
         document. `touch-action` is resolved as the *intersection* of the
         element and its ancestors, so `touch-action: none` on <html> also
         froze the drawer's own list: on iOS the menu could not be scrolled by
         finger at all, and a stray `touchend` could still trigger Safari's
         rubber-band / pull-to-refresh.

       What is left is the one lock that is both iOS-proof and layout-neutral:
       pinning the body out of flow at its current scroll offset for as long as
       the drawer is open, then putting the offset back on close. The document
       has nothing left to scroll (so wheel, touch and scroll keys all do
       nothing, without a single preventDefault), the header keeps its sticky
       position, and the drawer scrolls natively with `overscroll-behavior:
       contain` on the list so its momentum never chains to the page. */
    var lockY = 0;
    var locked = false;

    function lockPage() {
      if (locked) return;
      locked = true;
      lockY = window.scrollY || window.pageYOffset || 0;
      var style = document.body.style;
      style.top = -lockY + 'px';
      document.body.classList.add('nav-lock');
      document.documentElement.classList.add('nav-lock');
    }

    function unlockPage() {
      if (!locked) return;
      locked = false;
      document.body.classList.remove('nav-lock');
      document.documentElement.classList.remove('nav-lock');
      document.body.style.top = '';
      // Put the reader back exactly where they were: no jump, no scroll event
      // storm, no reflow of the content they were reading.
      if (lockY) window.scrollTo(0, lockY);
      lockY = 0;
    }

    var lastFocus = null;

    function closeNav() {
      if (!document.body.classList.contains('nav-open')) return;
      document.body.classList.remove('nav-open');
      document.documentElement.classList.remove('nav-open');
      btn.setAttribute('aria-expanded', 'false');
      btn.setAttribute('aria-label', 'Open menu');
      if (window.innerWidth > NAV_DRAWER_WIDTH) moreMenus.forEach(function (d) { d.open = false; });
      unlockPage();
      // Return focus to the control that opened the drawer, unless the reader
      // already moved on (e.g. they followed a link).
      if (lastFocus && lastFocus.isConnected && !links.contains(document.activeElement)) {
        try { lastFocus.focus({ preventScroll: true }); } catch (error) { /* ignore */ }
      }
      lastFocus = null;
    }

    function openNav() {
      if (document.body.classList.contains('nav-open')) return;
      lastFocus = document.activeElement;
      lockPage();
      document.body.classList.add('nav-open');
      document.documentElement.classList.add('nav-open');
      btn.setAttribute('aria-expanded', 'true');
      btn.setAttribute('aria-label', 'Close menu');
      if (window.innerWidth <= NAV_DRAWER_WIDTH) moreMenus.forEach(function (d) { d.open = true; });
    }

    btn.addEventListener('click', function () {
      document.body.classList.contains('nav-open') ? closeNav() : openNav();
    });
    backdrop.addEventListener('click', closeNav);
    links.addEventListener('click', function (event) {
      if (event.target.closest && event.target.closest('a')) closeNav();
    });
    // Desktop: close the "More" menu when clicking/tapping outside of it.
    document.addEventListener('click', function (event) {
      if (window.innerWidth <= NAV_DRAWER_WIDTH) return;
      moreMenus.forEach(function (details) {
        if (details.open && !details.contains(event.target)) details.open = false;
      });
    });
    document.addEventListener('keydown', function (event) {
      if (event.key === 'Escape') moreMenus.forEach(function (d) { d.open = false; });
    });
    document.addEventListener('keydown', function (event) {
      if (event.key !== 'Escape') return;
      if (!document.body.classList.contains('nav-open')) return;
      closeNav();
      try { btn.focus({ preventScroll: true }); } catch (error) { /* ignore */ }
    });
    /* Keyboard containment while the drawer is open: Tab cycles through the
       drawer instead of walking into the page hidden behind the backdrop.
       This is a keydown listener, not a scroll/touch interception, so it
       cannot interfere with panning or momentum. */
    document.addEventListener('keydown', function (event) {
      if (event.key !== 'Tab') return;
      if (!document.body.classList.contains('nav-open')) return;
      var items = focusables();
      if (!items.length) return;
      var first = items[0];
      var last = items[items.length - 1];
      var active = document.activeElement;
      if (!links.contains(active)) {
        event.preventDefault();
        (event.shiftKey ? last : first).focus();
      } else if (event.shiftKey && active === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && active === last) {
        event.preventDefault();
        first.focus();
      }
    });
    /* Escape when a <details> "More" menu swallowed it, and prevent the drawer
       from surviving into desktop layout. */
    window.addEventListener('resize', function () {
      if (window.innerWidth > NAV_DRAWER_WIDTH) closeNav();
    });
    window.addEventListener('pagehide', unlockPage);

    OS.closeNav = closeNav;
    OS.openNav = openNav;
  }

  /* Nav fit guard.
     Labels are never ellipsized (see `.nav-links a` in components.css), so
     something has to give when a row runs out of room — a wide locale
     (German "Sammlungen", Japanese "コレクション"), browser zoom, a large-text
     setting or the install pill appearing can all do it. Instead of clipping
     text we park the trailing links inside the "More" menu that is already
     there, and bring them back the moment room returns. Below the drawer
     breakpoint the guard stands down: the drawer lists every link. */
  function setupNavFit() {
    $$('.site-header .nav, .ap-header-inner').forEach(fitOneNav);
  }

  function fitOneNav(nav) {
    var wrap = nav.querySelector('.nav-links');
    if (!wrap || wrap.dataset.navFit === '1') return;
    var more = wrap.querySelector('.nav-more');
    var menu = more && more.querySelector('.nav-menu');
    if (!more || !menu) return;
    wrap.dataset.navFit = '1';

    // The collapsible labels are the direct <a> children that sit before the
    // "More" control. Captured once so a parked link can never be lost.
    var pool = [];
    Array.prototype.forEach.call(wrap.children, function (node) {
      if (node.tagName === 'A') pool.push(node);
    });
    if (!pool.length) return;

    // Parked links go at the top of the menu, above its static entries.
    var anchor = menu.firstElementChild;
    var parked = 0;

    function layout(n) {
      if (n === parked) return;
      parked = n;
      pool.forEach(function (link) { wrap.insertBefore(link, more); });
      pool.slice(pool.length - n).forEach(function (link) { menu.insertBefore(link, anchor); });
      wrap.classList.toggle('has-parked', n > 0);
    }

    function overflows() {
      // scrollWidth reports overflowing content even with overflow:hidden,
      // which is exactly the signal we need; the nav itself is checked too so
      // a wide controls group is caught as well.
      return (wrap.scrollWidth - wrap.clientWidth > 1) || (nav.scrollWidth - nav.clientWidth > 1);
    }

    function sync() {
      if (window.innerWidth <= NAV_DRAWER_WIDTH || document.body.classList.contains('nav-open')) {
        layout(0); // the drawer shows every link, so nothing stays parked
        return;
      }
      layout(0);
      var n = 0;
      // Keep at least "Home" in the row; everything else can live in "More".
      while (overflows() && n < pool.length - 1) { n += 1; layout(n); }
    }

    var frame = 0;
    function schedule() {
      if (frame) return;
      frame = window.requestAnimationFrame(function () { frame = 0; sync(); });
    }

    window.addEventListener('resize', schedule, { passive: true });
    // Translated labels change width, so re-measure on every language switch.
    window.addEventListener('i18n:changed', schedule);
    if (OS.on) OS.on('language:changed', schedule);
    // Web fonts land after first paint and shift every measurement.
    if (document.fonts && document.fonts.ready && document.fonts.ready.then) {
      document.fonts.ready.then(schedule, function () { /* ignore */ });
    }
    sync();
    OS.syncNavFit = schedule;
  }

  /* Install button.
     `beforeinstallprompt` is Chromium-only: it never fires on iOS Safari or
     Firefox, which between them are most of this site's audience. Waiting for
     it meant the header's Install button stayed at `display: none` forever on
     exactly the devices the catalog is for. So the button is revealed at boot
     and bound once — when the browser does hand us a native prompt we use it,
     otherwise the button opens the installation center, which is the real
     answer for a sideloading source (pick a client, add the feed). */
  var installEvent = null;

  function setupInstallPrompt() {
    var btn = document.querySelector('.install-prompt');
    if (!btn || btn.dataset.bound === '1') return;
    btn.dataset.bound = '1';
    btn.classList.add('is-visible');
    btn.addEventListener('click', function () {
      if (installEvent) {
        installEvent.prompt();
        if (installEvent.userChoice && installEvent.userChoice.then) {
          installEvent.userChoice.then(function (choice) {
            if (choice && choice.outcome === 'accepted') OS.toast('OmniSource installed');
            installEvent = null;
          }, function () { installEvent = null; });
        }
        return;
      }
      location.href = url('install/');
    });
  }

  window.addEventListener('beforeinstallprompt', function (event) {
    event.preventDefault();
    installEvent = event;
    var btn = document.querySelector('.install-prompt');
    if (btn) {
      btn.classList.add('is-visible');
      // Bound once at boot; this only refreshes the affordance's label so a
      // native install is offered instead of navigating.
      btn.setAttribute('data-native-install', '1');
    }
  });

  /* ============================================================================
     Motion: scroll reveal + count-up (respecting prefers-reduced-motion).
     ========================================================================== */
  /* [data-reveal] ships at opacity:0 (animations.css) and is only painted once
     something adds .is-revealed. Two things used to leave whole sections
     blank when you scrolled down to them:

       • the observer was armed once, over the nodes that existed at boot, and
         bailed out entirely when there were none — but almost every renderer
         injects its markup *after* that (the release feed on the home page,
         the whole grid on /collections/). Those nodes were never observed, so
         they kept opacity:0 forever: a heading with an empty body under it.
       • nothing ever re-checked. One missed callback was permanent.

     So: always arm, watch the DOM for late arrivals and hand them to the same
     observer, and sweep once after load for anything still invisible while
     actually on screen. */
  function setupReveal() {
    function show(node) { node.classList.add('is-revealed'); }

    if (OS.reducedMotion || !('IntersectionObserver' in window)) {
      $$('[data-reveal]').forEach(show);
      watchRevealAdditions(show);
      return;
    }

    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          show(entry.target);
          observer.unobserve(entry.target);
        }
      });
    }, { rootMargin: '0px 0px -36px 0px', threshold: 0.08 });

    function observe(node) {
      if (!node._omniRevealArmed) {
        node._omniRevealArmed = true;
        observer.observe(node);
      }
    }
    $$('[data-reveal]').forEach(observe);
    watchRevealAdditions(observe);

    /* Safety net: an element that is provably on screen but still transparent
       is a bug the reader can see, so believe the rect over the observer. */
    window.addEventListener('load', function () {
      setTimeout(function () {
        var height = window.innerHeight || document.documentElement.clientHeight;
        $$('[data-reveal]:not(.is-revealed)').forEach(function (node) {
          var rect = node.getBoundingClientRect();
          if (rect.height && rect.top < height && rect.bottom > 0) show(node);
        });
      }, 1200);
    });
  }

  /* Feed every [data-reveal] node that appears after boot to `handler`
     (observe it, or reveal it outright when motion is off). Debounced to one
     pass per frame: a catalog re-render adds a few hundred nodes at once and
     we only care about the final tree. */
  function watchRevealAdditions(handler) {
    if (!('MutationObserver' in window) || !document.body) return;
    var queued = false;
    var pending = [];
    function drain() {
      queued = false;
      var batch = pending;
      pending = [];
      batch.forEach(function (node) {
        if (!node.isConnected) return;
        if (node.matches && node.matches('[data-reveal]')) handler(node);
        if (node.querySelectorAll) $$('[data-reveal]', node).forEach(handler);
      });
    }
    var observer = new MutationObserver(function (records) {
      for (var i = 0; i < records.length; i += 1) {
        var added = records[i].addedNodes;
        for (var j = 0; j < added.length; j += 1) {
          if (added[j].nodeType === 1) pending.push(added[j]);
        }
      }
      if (pending.length && !queued) {
        queued = true;
        requestAnimationFrame(drain);
      }
    });
    observer.observe(document.body, { childList: true, subtree: true });
  }

  function animateCount(node, force) {
    if (node._omniCounting || (node._omniCounted && !force)) return;
    var raw = node.dataset.countValue != null ? String(node.dataset.countValue) : String(node.textContent);
    if (raw === '') return;
    // Non-numeric targets (e.g. "22/22") are rendered directly, no animation.
    if (!/^\d+(\.\d+)?$/.test(raw)) {
      node.textContent = raw;
      node.classList.add('os-count-done');
      node._omniCounted = true;
      return;
    }
    var target = parseFloat(raw);
    var suffix = node.dataset.countSuffix || '';
    var decimals = (raw.split('.')[1] || '').length;
    node._omniCounted = true;
    node._omniCounting = true;
    function finish() {
      node.textContent = target.toFixed(decimals) + suffix;
      node.classList.add('os-count-done');
      node._omniCounting = false;
    }
    if (OS.reducedMotion) {
      finish();
      return;
    }
    var start = null;
    var duration = 900;
    // Safety net: renderers whose requestAnimationFrame callbacks never fire
    // (headless capture, heavily throttled background tabs) would otherwise
    // sit at the starting number forever — land on the final value instead.
    var fallback = setTimeout(function () {
      if (node._omniCounting) finish();
    }, duration + 400);
    function frame(ts) {
      if (!node._omniCounting) return;
      if (start === null) start = ts;
      var p = Math.min(1, (ts - start) / duration);
      var eased = 1 - Math.pow(1 - p, 3);
      node.textContent = (target * eased).toFixed(decimals) + suffix;
      if (p < 1) {
        requestAnimationFrame(frame);
      } else {
        clearTimeout(fallback);
        finish();
      }
    }
    requestAnimationFrame(frame);
  }

  // Values for [data-count] nodes are set by page renderers *after* async
  // data loads, so arm a retry that animates as soon as a value appears
  // (and gives up after ~10 s, rendering whatever is there).
  function armCount(node, onDone) {
    if (node.dataset.countValue != null) {
      animateCount(node);
      if (onDone) onDone();
      return;
    }
    var tries = 0;
    (function tick() {
      if (!node.isConnected) return;
      if (node.dataset.countValue != null) {
        animateCount(node);
        if (onDone) onDone();
        return;
      }
      if (++tries > 50) {
        animateCount(node, true);
        return;
      }
      setTimeout(tick, 200);
    })();
  }

  function setupCounts() {
    var nodes = $$('[data-count]');
    if (!nodes.length) return;
    if (OS.reducedMotion || !('IntersectionObserver' in window)) {
      nodes.forEach(function (n) {
        n.classList.add('os-count');
        armCount(n);
      });
      return;
    }
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        var node = entry.target;
        if (node.dataset.countValue != null) {
          animateCount(node);
          observer.unobserve(node);
        } else {
          armCount(node, function () { observer.unobserve(node); });
        }
      });
    }, { threshold: 0.4 });
    nodes.forEach(function (n) {
      n.classList.add('os-count');
      observer.observe(n);
    });
  }

  /* Nav anchors (#catalog, #trending, #whats-new, …) point at sections that
     stay hidden until their feed arrives. Browsers refuse to scroll to a
     display:none element, so on a phone the drawer's "Trending" link looked
     completely dead for the seconds the feeds took: the drawer closed, the
     hash changed, nothing moved. Queue the jump and perform it the moment the
     section is revealed. */
  // Fix for #top — scrolling to a huge <main> element caused Safari "A problem repeatedly occurred" crash
  function setupTopAnchorFix() {
    document.addEventListener('click', function (event) {
      var link = event.target.closest && event.target.closest('a[href="#top"]');
      if (!link) return;
      event.preventDefault();
      // Scroll to absolute top without relying on element height
      try {
        if (OS.reducedMotion) {
          window.scrollTo(0, 0);
        } else {
          window.scrollTo({ top: 0, behavior: 'smooth' });
        }
      } catch (e) {
        window.scrollTo(0, 0);
      }
      try {
        history.replaceState(null, '', location.pathname + location.search);
      } catch (e) {}
      if (OS.closeNav) OS.closeNav();
    });
  }

  function setupTapButtons() {
    // Inject bottom nav + FABs on any page that doesn't have them (collections, sources, etc.)
    function ensureTapUI() {
      if (!document.querySelector('.bottom-nav')) {
        var nav = document.createElement('nav');
        nav.className = 'bottom-nav';
        nav.setAttribute('aria-label', 'Quick tap navigation');
        var root = (typeof ROOT !== 'undefined' ? ROOT : '') || '';
        // Use OS.url for proper base path handling if available
        function u(path) {
          try { return (window.OS && OS.url ? OS.url(path) : path); } catch(e) { return path; }
        }
        nav.innerHTML =
          '<a href="' + (window.OS ? OS.url('#top') : '#top') + '" class="bn-item" data-bn="home" aria-label="Home">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-5H9v5H4a1 1 0 0 1-1-1v-9.5Z"/></svg><span>Home</span></a>' +
          '<a href="' + u('#catalog') + '" class="bn-item" data-bn="apps" aria-label="All apps">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="7" height="7" rx="2"/><rect x="13.5" y="3.5" width="7" height="7" rx="2"/><rect x="3.5" y="13.5" width="7" height="7" rx="2"/><rect x="13.5" y="13.5" width="7" height="7" rx="2"/></svg><span>Apps</span></a>' +
          '<button class="bn-item bn-primary" type="button" data-open-palette aria-label="Search apps">' +
            '<span class="bn-primary-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/></svg></span><span>Search</span></button>' +
          '<a href="' + u('collections/') + '" class="bn-item" data-bn="collections" aria-label="Collections">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 3 7.5l9 4.5 9-4.5L12 3Z"/><path d="m3 12 9 4.5L21 12"/><path d="m3 16.5 9 4.5 9-4.5"/></svg><span>Stacks</span></a>' +
          '<a href="' + u('install/') + '" class="bn-item" data-bn="install" aria-label="Install guide">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v11m0 0 4-4m-4 4-4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2"/></svg><span>Install</span></a>';
        document.body.appendChild(nav);
      }
      if (!document.getElementById('fabTop')) {
        var stack = document.createElement('div');
        stack.className = 'fab-stack';
        stack.setAttribute('aria-label', 'Quick actions');
        stack.innerHTML =
          '<button class="fab" id="fabTop" type="button" aria-label="Back to top" title="Back to top">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5 5 12l1.4 1.4L11 9v10h2V9l4.6 4.4L19 12 12 5Z"/></svg></button>' +
          '<button class="fab fab-primary" id="fabBrowse" type="button" aria-label="Browse all apps" title="Browse apps">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="1.6" fill="currentColor"/><circle cx="8" cy="12" r="1.6" fill="currentColor"/><circle cx="8" cy="18" r="1.6" fill="currentColor"/></svg></button>';
        document.body.appendChild(stack);
      }
    }
    try { ensureTapUI(); } catch(e) {}
    var fabTop = document.getElementById('fabTop');
    var fabBrowse = document.getElementById('fabBrowse');
    var bottomNav = document.querySelector('.bottom-nav');
    var ticking = false;

    function updateFabs() {
      ticking = false;
      var y = window.scrollY || window.pageYOffset || 0;
      var showTop = y > 400;
      var showBrowse = y > 200;
      if (fabTop) fabTop.classList.toggle('is-visible', showTop);
      if (fabBrowse) fabBrowse.classList.toggle('is-visible', showBrowse);
      // Bottom nav active state based on scroll
      if (bottomNav) {
        var items = bottomNav.querySelectorAll('.bn-item[data-bn]');
        var catalog = document.getElementById('catalog');
        var homeActive = true;
        if (catalog) {
          var rect = catalog.getBoundingClientRect();
          if (rect.top < window.innerHeight * 0.5) homeActive = false;
        }
        items.forEach(function (it) {
          var active = false;
          if (it.dataset.bn === 'home') active = homeActive;
          if (it.dataset.bn === 'apps') active = !homeActive;
          it.classList.toggle('is-active', active);
          if (active) it.setAttribute('aria-current', 'page');
          else it.removeAttribute('aria-current');
        });
      }
    }

    window.addEventListener('scroll', function () {
      if (!ticking) {
        ticking = true;
        requestAnimationFrame(updateFabs);
      }
    }, { passive: true });

    if (fabTop) {
      fabTop.addEventListener('click', function () {
        try {
          if (OS.reducedMotion) window.scrollTo(0, 0);
          else window.scrollTo({ top: 0, behavior: 'smooth' });
        } catch (e) { window.scrollTo(0, 0); }
      });
    }
    if (fabBrowse) {
      fabBrowse.addEventListener('click', function () {
        var catalog = document.getElementById('catalog');
        if (catalog) {
          try {
            catalog.scrollIntoView({ behavior: OS.reducedMotion ? 'auto' : 'smooth', block: 'start' });
          } catch (e) { catalog.scrollIntoView(); }
        } else {
          // On other pages, go to home catalog
          try {
            var target = (window.OS && OS.url ? OS.url('#catalog') : '/#catalog');
            // If already on home, use hash; else navigate
            if (document.body && document.body.dataset.page === 'home') {
              location.hash = 'catalog';
            } else {
              location.href = target;
            }
          } catch (e) {
            // Root-relative, so the fallback still lands on the catalog when
            // the site is served from a sub-path (GitHub Pages project sites).
            location.href = url('/#catalog');
          }
        }
      });
    }
    updateFabs();
  }

  function setupDeferredAnchors() {
    var pending = null;
    var observer = null;

    function jumpTo(id) {
      var node = document.getElementById(id);
      if (!node || node.hidden) return false;
      node.scrollIntoView({ behavior: OS.reducedMotion ? 'auto' : 'smooth', block: 'start' });
      return true;
    }

    function stopWatching() {
      pending = null;
      if (observer) { observer.disconnect(); observer = null; }
    }

    function watch() {
      if (observer || !pending || !('MutationObserver' in window)) return;
      observer = new MutationObserver(function () {
        if (pending && jumpTo(pending)) stopWatching();
      });
      observer.observe(document.body, { subtree: true, attributes: true, attributeFilter: ['hidden'] });
      // A feed that never lands must not leave a watcher behind.
      setTimeout(stopWatching, 20000);
    }

    document.addEventListener('click', function (event) {
      var link = event.target.closest && event.target.closest('a[href^="#"]');
      if (!link) return;
      var id = decodeURIComponent(link.getAttribute('href').slice(1));
      if (!id) return;
      var node = document.getElementById(id);
      if (!node || !node.hidden) return;
      pending = id;
      watch();
    });
  }

  /* ============================================================================
     Scroll stability
     ----------------------------------------------------------------------------
     The home page un-hides whole sections as their feeds land (#trending,
     #featured, #statistics, #sourceHealth, #installGuide …) and every one of
     them sits *above* the catalog. Chrome absorbs that with native scroll
     anchoring; iOS Safari — the device this catalog exists for — has no
     scroll anchoring at all, so a reader halfway down the page was thrown
     several thousand pixels away each time a feed arrived. "Scrolling from
     top to bottom" jumped around for the first few seconds of every visit.

     stableScroll() measures a landmark at the top of the viewport, runs the
     DOM work, then re-pins the scroll offset by however much the landmark
     moved. Where the browser already anchored (Chromium), the landmark did
     not move and the correction is zero, so the two never fight.
     ========================================================================== */
  function scrollTo(y) {
    // html { scroll-behavior: smooth } would animate a *correction*, which
    // reads as a second, slower jump. Snap, always.
    if ('scrollBehavior' in document.documentElement.style) {
      window.scrollTo({ top: y, left: 0, behavior: 'auto' });
    } else {
      window.scrollTo(0, y);
    }
  }

  /* The element a reader is looking at right now: the deepest one under the
     top edge of the viewport that scrolls with the document (sticky/fixed
     chrome is skipped — it never moves, so it cannot report a shift). Falls
     back to the section it belongs to, which survives an innerHTML re-render
     of its own contents. */
  function scrollLandmark() {
    var x = Math.max(2, Math.round((window.innerWidth || 360) / 2));
    var stack = document.elementsFromPoint ? document.elementsFromPoint(x, 2) : [];
    for (var i = 0; i < stack.length; i += 1) {
      var node = stack[i];
      if (node === document.body || node === document.documentElement) continue;
      var position = '';
      try { position = window.getComputedStyle(node).position; } catch (e) { position = ''; }
      if (position === 'fixed' || position === 'sticky') continue;
      return node;
    }
    return null;
  }

  function landmarkSection(node) {
    var section = node && node.closest ? node.closest('main > section[id], main[id]') : null;
    return section || node;
  }

  function usable(node) {
    return Boolean(node) && node.isConnected && !node.hidden && node.getBoundingClientRect().height > 0;
  }

  OS.stableScroll = function (work) {
    var y = window.scrollY || window.pageYOffset || 0;
    // At the top there is nothing to preserve, and measuring costs a layout.
    if (y < 24) { work(); return; }

    var deep = scrollLandmark();
    var section = landmarkSection(deep) || $('main');
    var deepWas = usable(deep);
    var sectionWas = usable(section);
    var deepBefore = deepWas ? deep.getBoundingClientRect().top : null;
    var sectionBefore = sectionWas ? section.getBoundingClientRect().top : null;

    work();

    // Prefer the deep landmark: it also reports growth *inside* a section,
    // which is what a rail re-rendering its cards does. If it was replaced or
    // hidden mid-render, fall back to the section around it.
    var delta = null;
    if (deepWas && deepBefore !== null && usable(deep)) {
      delta = deep.getBoundingClientRect().top - deepBefore;
    } else if (sectionWas && sectionBefore !== null && usable(section)) {
      delta = section.getBoundingClientRect().top - sectionBefore;
    }
    if (delta === null || Math.abs(delta) < 1) return;
    scrollTo(Math.max(0, y + delta));
  };

  /* ============================================================================
     Scroll affordances: reading progress, back-to-top, scroll hints
     ========================================================================== */
  function onScroll(handler) {
    var ticking = false;
    window.addEventListener('scroll', function () {
      if (!ticking) {
        ticking = true;
        requestAnimationFrame(function () { ticking = false; handler(); });
      }
    }, { passive: true });
    window.addEventListener('resize', function () { handler(); }, { passive: true });
    handler();
  }

  /* Document height is read at most a couple of times a second on purpose:
     scrollHeight forces a layout flush, and reading it on every scrolled
     frame — right after writing the progress bar's transform — is exactly the
     read/write thrash that makes a long page feel sticky on a phone. */
  var docHeight = 0;
  var docHeightStamp = 0;
  function measureDocument(now) {
    if (!docHeight || now - docHeightStamp > 400) {
      docHeightStamp = now;
      docHeight = document.documentElement.scrollHeight || 0;
    }
    return docHeight;
  }

  function scrollMetrics() {
    var y = window.scrollY || window.pageYOffset || 0;
    var max = Math.max(0, measureDocument(Date.now()) - (window.innerHeight || 0));
    return { y: y, max: max, ratio: max > 0 ? Math.min(1, y / max) : 0 };
  }

  /* 2px reading-progress line + the back-to-top bead. Injected, like the
     mobile nav drawer, so the generated app pages and every hand-written
     section page get them without touching their markup. Both stay out of
     the way until there is something to report: the line is invisible at the
     very top and the bead only appears once a screenful has gone past. */
  function setupScrollAffordances() {
    if (!document.body) return;

    var wrap = $('.scroll-progress');
    if (!wrap) {
      wrap = document.createElement('div');
      wrap.className = 'scroll-progress';
      wrap.id = 'scrollProgress';
      wrap.setAttribute('aria-hidden', 'true');
      wrap.innerHTML = '<i id="scrollProgressBar"></i>';
      document.body.appendChild(wrap);
    }
    var bar = wrap.firstElementChild;

    var toTop = $('#backToTop');
    if (!toTop) {
      toTop = document.createElement('button');
      toTop.type = 'button';
      toTop.id = 'backToTop';
      toTop.className = 'to-top';
      toTop.setAttribute('aria-label', 'Back to top');
      toTop.setAttribute('title', 'Back to top');
      toTop.setAttribute('data-i18n-aria-label', 'tabs.backToTop');
      toTop.setAttribute('data-i18n-title', 'tabs.backToTop');
      toTop.innerHTML = '<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 19V5M5.5 11.5 12 5l6.5 6.5"/></svg>';
      document.body.appendChild(toTop);
    }

    var idleTimer = null;
    // A resize (or a phone rotating) changes the document height; drop the
    // cached measurement instead of waiting for the throttle to expire.
    window.addEventListener('resize', function () { docHeight = 0; }, { passive: true });
    onScroll(function () {
      var m = scrollMetrics();
      if (bar) bar.style.transform = 'scaleX(' + m.ratio.toFixed(4) + ')';
      if (wrap) wrap.classList.toggle('is-visible', m.ratio > 0.004 && m.ratio < 0.999);
      if (toTop) {
        toTop.classList.toggle('is-visible', m.y > Math.max(700, (window.innerHeight || 700) * 1.25));
      }
      // Pause the ambient body::before drift while a scroll is in flight: it is
      // a fixed, full-viewport layer, so every frame of it competes with the
      // scroll itself (see tokens.css).
      document.body.classList.add('is-scrolling');
      clearTimeout(idleTimer);
      idleTimer = setTimeout(function () {
        document.body.classList.remove('is-scrolling');
      }, 180);
    });

    if (toTop) {
      toTop.addEventListener('click', function () {
        // Deliberate user action, so smooth is right here — unless the reader
        // asked for less motion, in which case scrollTo() already snapped.
        if (!OS.reducedMotion && 'scrollBehavior' in document.documentElement.style) {
          window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
        } else {
          scrollTo(0);
        }
        var top = $('#top') || document.body;
        if (top && top.focus) {
          try {
            if (!top.hasAttribute('tabindex')) top.setAttribute('tabindex', '-1');
            top.focus({ preventScroll: true });
          } catch (e) { /* focus is a nicety, not the point */ }
        }
      });
    }
  }

  /* Horizontal rails (the tab bars) fade their edges only while they actually
     overflow in that direction — the fade is the "more this way" hint. */
  function setupScrollHints() {
    var rails = $$('[data-scroll-hints]');
    if (!rails.length) return;
    function sync(rail) {
      var host = rail.closest('[data-scroll-hint-host]') || rail.parentElement;
      if (!host) return;
      var overflow = rail.scrollWidth - rail.clientWidth > 2;
      host.classList.toggle('can-scroll-start', overflow && rail.scrollLeft > 4);
      host.classList.toggle('can-scroll-end', overflow && rail.scrollLeft < rail.scrollWidth - rail.clientWidth - 4);
    }
    rails.forEach(function (rail) {
      rail.addEventListener('scroll', function () { sync(rail); }, { passive: true });
      window.addEventListener('resize', function () { sync(rail); }, { passive: true });
      sync(rail);
    });
    // Labels change width on a language switch, so re-measure then too.
    window.addEventListener('i18n:changed', function () {
      rails.forEach(function (rail) { sync(rail); });
    });
    OS.syncScrollHints = function () { rails.forEach(sync); };
  }

  /* ============================================================================
     Section tabs
     ----------------------------------------------------------------------------
     A sticky row of tabs pinned under the header. It is navigation, not a
     widget: the links are real anchors (so they work with JavaScript off, in
     a new tab, and for screen readers), the current one is marked with
     aria-current, and tabs whose section has not arrived yet are dropped
     rather than left dead. js/core.js owns the scroll-spy; js/site.js calls
     OS.refreshSectionTabs() once a feed changes which sections exist.
     ========================================================================== */
  /* Where the sticky bars pin, read from the same custom property the CSS
     uses so the two can never drift. Cached: the scroll-spy asks on every
     frame and getComputedStyle() is not free. */
  var stickyOffsetCache = null;
  function stickyOffset() {
    if (stickyOffsetCache === null) {
      var raw = '';
      try {
        raw = window.getComputedStyle(document.documentElement).getPropertyValue('--sticky-offset');
      } catch (e) { raw = ''; }
      var value = parseFloat(raw);
      stickyOffsetCache = Number.isFinite(value) && value > 0 ? value : 74;
    }
    return stickyOffsetCache;
  }

  function setupSectionTabs() {
    var bar = $('#sectionTabs');
    if (!bar) return;
    var rail = $('.section-tabs-inner', bar);
    var tabs = $$('.section-tab[data-target]', bar);
    if (!tabs.length) return;

    function sectionOf(tab) {
      return document.getElementById(tab.dataset.target);
    }

    /* Tab/section pairs, rebuilt when a section appears or disappears rather
       than on every scrolled frame. */
    var pairs = [];
    function remeasure() {
      pairs = tabs
        .map(function (tab) { return { tab: tab, node: sectionOf(tab) }; })
        .filter(function (pair) { return pair.node && !pair.node.hidden; });
    }
    remeasure();
    window.addEventListener('resize', function () {
      stickyOffsetCache = null;
      remeasure();
    }, { passive: true });

    function activate(tab) {
      tabs.forEach(function (other) {
        var on = other === tab;
        if (on) other.setAttribute('aria-current', 'true');
        else other.removeAttribute('aria-current');
        other.classList.toggle('active', on);
      });
      // Keep the chosen tab inside the rail without scrolling the document:
      // scrollIntoView() would drag the page vertically with it.
      if (!rail) return;
      var left = tab.offsetLeft - rail.clientWidth / 2 + tab.offsetWidth / 2;
      var max = rail.scrollWidth - rail.clientWidth;
      var want = Math.max(0, Math.min(left, max));
      if (Math.abs(want - rail.scrollLeft) > 2) rail.scrollLeft = want;
    }

    function spy() {
      var line = stickyOffset() + Math.max(80, (window.innerHeight || 600) * 0.28);
      var current = null;
      for (var i = 0; i < pairs.length; i += 1) {
        // A section with no box (still hidden, or laid out by an engine that
        // reports zeros) cannot be the one the reader is in.
        var rect = pairs[i].node.getBoundingClientRect();
        if (!rect.height) continue;
        if (!current) current = pairs[i];
        if (rect.top <= line) current = pairs[i];
      }
      // Nothing measurable: keep whatever the markup started with.
      if (!current || current.tab.getAttribute('aria-current')) return;
      activate(current.tab);
    }

    /* Drop tabs whose section never arrives (no trending data, say) instead of
       shipping a button that does nothing. Runs after every render pass. */
    OS.refreshSectionTabs = function () {
      var any = 0;
      tabs.forEach(function (tab) {
        var node = sectionOf(tab);
        // #top is <main> itself and always there; the rest are data-driven.
        var missing = Boolean(node) && node.hidden;
        tab.hidden = missing;
        if (!missing) any += 1;
      });
      bar.hidden = any === 0;
      remeasure();
      spy();
      if (OS.syncScrollHints) OS.syncScrollHints();
    };

    bar.addEventListener('click', function (event) {
      var tab = event.target.closest ? event.target.closest('.section-tab') : null;
      if (!tab) return;
      // Let the browser follow the anchor (and let setupDeferredAnchors queue
      // the jump when the section is still hidden); just paint the state now.
      activate(tab);
      /* …except for #top, which is <main> itself. Take that jump over: the
         target has to be the true top of the document rather than wherever
         scroll-padding leaves main's border box, and the hash should still
         read #top afterwards (preventDefault would otherwise drop it). */
      if (tab.dataset.target !== 'top' || !document.getElementById('top')) return;
      event.preventDefault();
      if (!OS.reducedMotion && 'scrollBehavior' in document.documentElement.style) {
        window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
      } else {
        scrollTo(0);
      }
      try {
        history.replaceState(null, '', location.pathname + location.search + '#top');
      } catch (e) { /* sandboxed frame */ }
    });

    // Roving arrow-key navigation across the rail, as for any tab strip.
    bar.addEventListener('keydown', function (event) {
      if (['ArrowRight', 'ArrowLeft', 'Home', 'End'].indexOf(event.key) === -1) return;
      var live = tabs.filter(function (tab) { return !tab.hidden; });
      if (live.length < 2) return;
      var index = live.indexOf(document.activeElement);
      if (index === -1) return;
      event.preventDefault();
      var next;
      if (event.key === 'Home') next = live[0];
      else if (event.key === 'End') next = live[live.length - 1];
      else {
        // Arrows follow the reading direction: the site ships Arabic, where
        // "right" is the previous tab.
        var forward = (event.key === 'ArrowRight') !== (document.documentElement.dir === 'rtl');
        next = live[(index + (forward ? 1 : -1) + live.length) % live.length];
      }
      if (next && next.focus) next.focus();
    });

    onScroll(spy);
    OS.refreshSectionTabs();
  }

  /* ------------------------------------------------------------------ boot */
  function boot() {
    // Theme (also applied pre-paint by the inline bootstrap in <head>).
    var stored = 'auto';
    try { stored = localStorage.getItem('omnisource-theme') || 'auto'; } catch (e) { /* ignore */ }
    setTheme(THEMES.indexOf(stored) !== -1 ? stored : 'auto');

    // Theme + view toggles.
    var themeButton = $('#themeButton');
    if (themeButton) {
      // Marks the button as claimed so js/modules/theme.js (module entry)
      // never binds a second toggle handler.
      themeButton.dataset.themeClaimed = '1';
      themeButton.addEventListener('click', cycleTheme);
    }
    var viewToggle = $('#viewToggle');
    if (viewToggle) {
      viewToggle.addEventListener('click', function () {
        var compact = document.documentElement.dataset.view === 'compact';
        document.documentElement.dataset.view = compact ? 'grid' : 'compact';
        try { localStorage.setItem('omnisource-view', compact ? 'grid' : 'compact'); } catch (e) { /* ignore */ }
        viewToggle.setAttribute('aria-pressed', String(!compact));
        viewToggle.setAttribute('aria-label', compact ? 'Use compact view' : 'Use grid view');
        viewToggle.title = compact ? 'Compact view' : 'Grid view';
      });
    }

    // Footer year.
    var year = $('#year');
    if (year) year.textContent = String(new Date().getFullYear());

    setupQrButton();
    setupHeaderState();
    setupMobileNav();
    setupNavFit();
    setupInstallPrompt();
    setupTopAnchorFix();
    setupTapButtons();
    setupDeferredAnchors();
    setupScrollAffordances();
    setupScrollHints();
    setupSectionTabs();
    setupReveal();
    setupCounts();
    registerServiceWorker();

    // When the language changes after boot, re-render the open palette so
    // its chrome (Recent / Popular / Categories / empty states) follows.
    // Static [data-i18n] markup is handled by OmniI18n itself.
    window.addEventListener('i18n:changed', function () {
      try {
        if (Palette.isOpen && Palette.input) Palette.render(Palette.input.value || '');
      } catch (e) { /* palette not initialized on this page */ }
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
